# -*- coding: utf-8 -*-
"""Marvel.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14UFttKulwa7H89z-NH0a-7lzEOP0tzGV
"""

from os import access
!pip install requests pandas -q #instalar biblioteca pandas que organiza dados!

import requests # usado para requisiçao de http chamar a API e pedor os dados
import pandas as pd # Acessa o conteudo da biblioteca panda pd e manipula analisa tabela (dataframe)
import hashlib # importa outra biblioteca que fornece algoritimos hash MD5 (exigencia da API da marvel)
import time # Tempo (exigencia para autenticar com API)
from datetime import datetime # pacote, pode ser tratado como uma funçao que esta dentro do pacote dentro de uma biblioteca
import getpass # sistema de senha uma especie de bloqueio com palavra chave
from IPython.display import display,HTML #utilizado no colab ou no jupyter

print('bibliotecas  intaladas')

#class Name
class api_cliente:
  def __init__ (self, public_key, private_key): #molde APi cliente (criando algo) init(marcação, inicia a caracteristicas relacionadas a self public.k e private.k modifica o init)
      self.public_key = public_key
      self.private_key = private_key
      self.base_url = 'https://gateway.marvel.com/v1/public/'


  def _parans(self):
    time_stanp = str(int(time.time()))
    print (time_stanp)
    resstring= time_stanp + self.private_key + self.public_key
    hassmd5= hashlib.md5(resstring.encode()).hexdigest() #parametros da matematica criptografando

    return {
      'ts':time_stanp,
      'apikey': self.public_key,
      'hash': hassmd5
      }

print('Classe criada')